Resources:
  Bucket:
    Type: 'AWS::S3::Bucket'
    Properties: 
      BucketName: 'kccatpics1123333337'
  Instance:
    Type: 'AWS::EC2::Instance'
    Properties: 
      InstanceType: 't2.micro'
      ImageId: 'ami-0230bd60aa48260c6'
  
